-- Trainerize library refresh, 2 Aug 2026 — 36 new custom exercises Esther added since
-- the 9 Jul import (e.g. Seated Dumbbell Hammer Curl, Half kneeling Pallof Press Hold,
-- both with real videos). Guarded with a NOT EXISTS check per row so this is safe to
-- re-run — the exercises table has no unique constraint on trainerize_id.

INSERT INTO exercises (name, source, trainerize_id, trainerize_custom, archetypes, movement_type, muscle_groups, equipment, tags, difficulty, intensity_tiers, coaching_cue, default_mod, image_url, video_url)
SELECT * FROM (VALUES
  ('A Frame to squat', 'trainerize', '17769437', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/cbxBlwIfioU/mqdefault.jpg', 'https://www.youtube.com/watch?v=cbxBlwIfioU'),
  ('Across body hammer curl', 'trainerize', '17796592', TRUE, '{}'::text[], NULL::text, ARRAY['Bicep']::text[], ARRAY['Dumbbell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/qmQkt1Y-FX8/mqdefault.jpg', 'https://www.youtube.com/watch?v=qmQkt1Y-FX8'),
  ('Banded shoulder distraction', 'trainerize', '17850923', TRUE, '{}'::text[], NULL::text, ARRAY['Shoulder (front)','Shoulder (rear)','Shoulder (side)']::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/VylnH1wKvsk/mqdefault.jpg', 'https://www.youtube.com/watch?v=VylnH1wKvsk'),
  ('Banded tricep extension (no anchor)', 'trainerize', '17796609', TRUE, '{}'::text[], NULL::text, ARRAY['Triceps']::text[], ARRAY['Bands (handles)','Bands (loops)']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/9aSpza-1vUg/mqdefault.jpg', 'https://www.youtube.com/watch?v=9aSpza-1vUg'),
  ('Bottoms up Kettlebell Carry', 'trainerize', '17787064', TRUE, '{}'::text[], NULL::text, ARRAY['Abs','Shoulder (front)','Shoulder (rear)','Shoulder (side)']::text[], ARRAY['Kettlebell']::text[], ARRAY['Unilateral']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/mLyUd0Dsim4/mqdefault.jpg', 'https://www.youtube.com/watch?v=mLyUd0Dsim4'),
  ('Cable rotational punch', 'trainerize', '17770116', TRUE, '{}'::text[], NULL::text, '{}'::text[], ARRAY['Bands (handles)','Bands (loops)']::text[], ARRAY['Vertical push']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/vlIRAwXSg9g/mqdefault.jpg', 'https://www.youtube.com/watch?v=vlIRAwXSg9g'),
  ('Childs pose with side reach', 'trainerize', '17769422', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/08hDppgS370/mqdefault.jpg', 'https://www.youtube.com/watch?v=08hDppgS370'),
  ('Chin tucks with wall', 'trainerize', '17794817', TRUE, '{}'::text[], NULL::text, ARRAY['Neck']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/C7SEZXN-PCM/mqdefault.jpg', 'https://www.youtube.com/watch?v=C7SEZXN-PCM'),
  ('Close grip DB floor press', 'trainerize', '17850910', TRUE, '{}'::text[], NULL::text, ARRAY['Triceps']::text[], ARRAY['Dumbbell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/x5STvCViQSE/mqdefault.jpg', 'https://www.youtube.com/watch?v=x5STvCViQSE'),
  ('DB RDL', 'trainerize', '17769648', TRUE, '{}'::text[], NULL::text, ARRAY['Glutes','Hamstrings']::text[], ARRAY['Dumbbell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/CBOhr6H7BEY/mqdefault.jpg', 'https://www.youtube.com/watch?v=CBOhr6H7BEY'),
  ('Doorway chest stretch', 'trainerize', '17796610', TRUE, '{}'::text[], NULL::text, ARRAY['Chest (inner)','Chest (mid)','Chest (upper)']::text[], '{}'::text[], ARRAY['Static stretches']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/O8rJw_TmC1Y/mqdefault.jpg', 'https://www.youtube.com/watch?v=O8rJw_TmC1Y'),
  ('Half kneeling Pallof Press Hold', 'trainerize', '17857585', TRUE, '{}'::text[], NULL::text, ARRAY['Abs']::text[], ARRAY['Bands (handles)','Bands (loops)']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/OXbZpZyQE7Y/mqdefault.jpg', 'https://www.youtube.com/watch?v=OXbZpZyQE7Y'),
  ('Half kneeling single arm should press', 'trainerize', '17770011', TRUE, '{}'::text[], NULL::text, ARRAY['Shoulder (front)']::text[], ARRAY['Bands (loops)']::text[], '{}'::text[], NULL::integer, '{}'::text[], 'Face away from the anchor
Band low', NULL::text, 'https://i.ytimg.com/vi/1WJGN6q-CKI/mqdefault.jpg', 'https://www.youtube.com/watch?v=1WJGN6q-CKI'),
  ('Laying hamstring curl with DB', 'trainerize', '17795014', TRUE, '{}'::text[], NULL::text, ARRAY['Hamstrings']::text[], ARRAY['Dumbbell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/QwK97FU9fII/mqdefault.jpg', 'https://www.youtube.com/watch?v=QwK97FU9fII'),
  ('Loaded lateral deadbug', 'trainerize', '17787078', TRUE, '{}'::text[], NULL::text, ARRAY['Abs']::text[], ARRAY['Bands (handles)','Bands (loops)']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/mSFI_GcxsKc/mqdefault.jpg', 'https://www.youtube.com/watch?v=mSFI_GcxsKc'),
  ('Med ball rotational throw', 'trainerize', '17786982', TRUE, '{}'::text[], NULL::text, ARRAY['Obliques','Shoulder (front)','Shoulder (side)']::text[], ARRAY['Medicine ball']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/MA5W6TA768k/mqdefault.jpg', 'https://www.youtube.com/watch?v=MA5W6TA768k'),
  ('Open the Gate', 'trainerize', '17793288', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/1cpY_x7yr8c/mqdefault.jpg', 'https://www.youtube.com/watch?v=1cpY_x7yr8c'),
  ('Pancake stretch', 'trainerize', '17769431', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], 'Sit on block 
Legs bent
Practise rotations feet in and out', NULL::text, 'https://i.ytimg.com/vi/6WSOqW13NzY/mqdefault.jpg', 'https://www.youtube.com/watch?v=6WSOqW13NzY'),
  ('Parallel Ring Row', 'trainerize', '17769632', TRUE, '{}'::text[], NULL::text, ARRAY['Back (middle)','Bicep']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/2mKpw0PuE2Y/mqdefault.jpg', 'https://www.youtube.com/watch?v=2mKpw0PuE2Y'),
  ('Prone quad stretch band assisted', 'trainerize', '17848131', TRUE, '{}'::text[], NULL::text, ARRAY['Quads']::text[], '{}'::text[], ARRAY['Static stretches']::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/B62rtjhWQqs/mqdefault.jpg', 'https://www.youtube.com/watch?v=B62rtjhWQqs'),
  ('Rear foot elevated goblet split squat', 'trainerize', '17770050', TRUE, '{}'::text[], NULL::text, ARRAY['Glutes','Hamstrings','Quads']::text[], ARRAY['Dumbbell','Kettlebell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/8CzyzcMeus4/mqdefault.jpg', 'https://www.youtube.com/watch?v=8CzyzcMeus4'),
  ('Scapular depression', 'trainerize', '17794821', TRUE, '{}'::text[], NULL::text, ARRAY['Back (middle)']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/5v6S4ahgU38/mqdefault.jpg', 'https://www.youtube.com/watch?v=5v6S4ahgU38'),
  ('Scapular retraction', 'trainerize', '17794823', TRUE, '{}'::text[], NULL::text, ARRAY['Back (middle)']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/UHlhyti-RBQ/mqdefault.jpg', 'https://www.youtube.com/watch?v=UHlhyti-RBQ'),
  ('Scapular squeeze', 'trainerize', '17794997', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/QN1oZVMMRjE/mqdefault.jpg', 'https://www.youtube.com/watch?v=QN1oZVMMRjE'),
  ('Seated Dumbbell Hammer Curl', 'trainerize', '17857588', TRUE, '{}'::text[], NULL::text, ARRAY['Bicep']::text[], ARRAY['Dumbbell']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/1sTqQ0EZO9Q/mqdefault.jpg', 'https://www.youtube.com/watch?v=1sTqQ0EZO9Q'),
  ('Segmental rolling - lower', 'trainerize', '17794871', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/KMXNqt_EjkY/mqdefault.jpg', 'https://www.youtube.com/watch?v=KMXNqt_EjkY'),
  ('Segmental rolling - upper', 'trainerize', '17794866', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/USzWAV_TeOo/mqdefault.jpg', 'https://www.youtube.com/watch?v=USzWAV_TeOo'),
  ('Single leg sit to stand', 'trainerize', '17796614', TRUE, '{}'::text[], NULL::text, ARRAY['Quads']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], 'Stage 1 -  Raise non working foot on yoga block push through working leg - 3-4 secs lower

Sit on the edge of the chair. Extend one leg straight out in front of you with the heel touching the floor. Keep the other foot flat under your knee

Stage 2 - Elevate chair', NULL::text, 'https://i.ytimg.com/vi/K8lvOfClXYI/mqdefault.jpg', 'https://www.youtube.com/watch?v=K8lvOfClXYI'),
  ('Single side suitcase deadlift', 'trainerize', '17794720', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/85jrBIjMk-o/mqdefault.jpg', 'https://www.youtube.com/watch?v=85jrBIjMk-o'),
  ('Skydiver', 'trainerize', '17819768', TRUE, '{}'::text[], NULL::text, ARRAY['Glutes']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/2l45wWnFXck/mqdefault.jpg', 'https://www.youtube.com/watch?v=2l45wWnFXck'),
  ('Suitcase march', 'trainerize', '17796601', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/-n8CxwQwB-4/mqdefault.jpg', 'https://www.youtube.com/watch?v=-n8CxwQwB-4'),
  ('Support cross legged sit', 'trainerize', '17770141', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], ARRAY['Mobility']::text[], NULL::integer, '{}'::text[], 'THE goal position. Progression: hands behind → back to wall → unsupported → build duration

then without block', NULL::text, 'https://i.ytimg.com/vi/Q7JCsl3Dodc/mqdefault.jpg', 'https://www.youtube.com/watch?v=Q7JCsl3Dodc'),
  ('Thoracic rotation - shoulder locked', 'trainerize', '17769414', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/f0IK6VYh0RI/mqdefault.jpg', 'https://www.youtube.com/watch?v=f0IK6VYh0RI'),
  ('Trap bar march', 'trainerize', '17848115', TRUE, '{}'::text[], NULL::text, '{}'::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], 'Lower body stamina. Glutes hamstrings. Core. Upperback. Grip. hand endurance', NULL::text, 'https://i.ytimg.com/vi/4SZnh6-8aTk/mqdefault.jpg', 'https://www.youtube.com/watch?v=4SZnh6-8aTk'),
  ('TRX Cossack squat', 'trainerize', '17786989', TRUE, '{}'::text[], NULL::text, ARRAY['Adductors','Glutes','Hamstrings','Quads']::text[], ARRAY['Suspension']::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/X6QpPWqupKI/mqdefault.jpg', 'https://www.youtube.com/watch?v=X6QpPWqupKI'),
  ('TRX Single leg RDL', 'trainerize', '17778022', TRUE, '{}'::text[], NULL::text, ARRAY['Hamstrings']::text[], '{}'::text[], '{}'::text[], NULL::integer, '{}'::text[], NULL, NULL::text, 'https://i.ytimg.com/vi/wdpixkZe2WY/mqdefault.jpg', 'https://www.youtube.com/watch?v=wdpixkZe2WY')
) AS v(name, source, trainerize_id, trainerize_custom, archetypes, movement_type, muscle_groups, equipment, tags, difficulty, intensity_tiers, coaching_cue, default_mod, image_url, video_url)
WHERE NOT EXISTS (
  SELECT 1 FROM exercises e WHERE e.trainerize_id = v.trainerize_id
);
